name: Publish Images
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    # paths:
    #   - '**.py'
    tags:
        - "v*.*"
  
  workflow_dispatch:

    # git tag -a v1.0
    # git push origin v1.0

  # schedule:
  #     - cron: "*/2 * * * *"
env:
  tag: latest
jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   PROD_IMAGE: ghcr.io/duyhenryer/learn-git-actions:edge
    #   HUB_PULL_SECRET: NA
    steps:
      - name: Fetch code
        uses: actions/checkout@v2
      - name: Build and Push to the DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: duyhenryer/me:tag
          
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: setup ssh
        env:
          PRIV_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIV_KEY" > id_rsa
          chmod 600 id_rsa
      - name: Pull image and start docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa root@${{ secrets.IP }} 'cd /data/me && docker-compose pull && docker-compose up -d'
