name: Publish Images
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    # paths:
    #   - '**.py'
    tags:
        - "v*.*"
  
  workflow_dispatch:

    # git tag -a v1.0
    # git push origin v1.0

  # schedule:
  #     - cron: "*/2 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   PROD_IMAGE: ghcr.io/duyhenryer/learn-git-actions:edge
    #   HUB_PULL_SECRET: NA
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/me:latest