name: Publish Images
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  workflow_dispatch:
    # paths:
    #   - '**.py'
    # tags:
    #     - "v*.*"
    # git tag -a v1.0
    # git push origin v1.0

  # schedule:
  #     - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   PROD_IMAGE: ghcr.io/duyhenryer/learn-git-actions:edge
    #   HUB_PULL_SECRET: NA
    steps:
      - name: Fetch code
        uses: actions/checkout@v2
      - name: Build and Push to the DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: duyhenryer/me
          tag_with_sha: true
